name: gfs
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.2
  percent_indicator: ^3.4.0
  flutter_svg: ^0.23.0+1
  get: ^4.6.1
  line_icons: ^2.0.1
  flutter_custom_clippers: ^2.0.0
  card_swiper: ^2.0.1
  fl_chart: ^0.41.0
  charts_flutter:
  calendar_agenda: any
  syncfusion_flutter_calendar: any
  #Local database
  path: ^1.8.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive database generators
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.11.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/dark/gf_dark_launcher.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/logo/dark/
    - assets/logo/light/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/PS.ttf
          style: normal
          weight: 700
    - family: Sifonn
      fonts:
        - asset: assets/fonts/SIFONN_BASIC_OUTLINE.otf
          style: normal
          weight: 700

